Repository nagatapote/scroll-movie, pull requests merged in 2021-09, with the labels that each got.

#38 feat: add preload times
  src/ScrollMovie.tsx
Labels: enhancement

#39 Safariで下までスクロールしすぎた場合の対策
  src/ScrollMovie.tsx
Labels: fix

#40 Safariで下までスクロールしすぎた場合の対策2
  src/ScrollMovie.tsx
Labels: fix

#41 Release/1.0.10
  package.json
  src/ScrollMovie.tsx
Labels: release
