Repository nagatapote/scroll-movie, pull requests merged in 2022-03, with the labels that each got.

#43 fix: LPの修正
  README.md
  demo.css
  develop.html
  img/getImage.png
  img/imageSize.png
  img/scrollsPerImage.png
  img/tracks.png
  index.html
Labels: fix, enhancement

#48 feature: meta情報の追加
  develop.html
  index.html
  scroll-movie/images/ogp.png
Labels: enhancement

#49 feat(template)
  develop.html
Labels: enhancement

#50 fix: preloadtimes
  develop.html
  src/ScrollMovie.tsx
Labels: fix
